### ISSUE TITLE
Search by postal code 

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/RateTheLandlord#111]

**Comment by stephenmartin2951** [comment]
Hi Kellen, I added this feature if you'll allow me to made a pull request.

**Comment by kellenwiltshire** [comment]
Hi @stephenmartin2951 , thank you for contributing. I am not seeing any reason why you shouldn't be able to commit and make a PR. If you are getting a specific error let me know and I will try and address it.

Thank you,

**Comment by stephenmartin2951** [comment]
Thanks Kellen. When trying to make a pull request it is telling me permission denied.

**Comment by stephenmartin2951** [comment]
I am dumb :)

**Comment by kellenwiltshire** [comment]
Thanks for your help on this @stephenmartin2951. Feel free to keep assisting if you want! Send us an email at contact@ratethelandlord.org
