### ISSUE TITLE
Buttons and countries blend together on mobile

### ISSUE THREAD

**Issue by RateTheLandlordAdmin** [RateTheLandlord/RateTheLandlord#188]
Maybe make the buttons smaller or less bold or something so its easier to delineate between country and buttons: 

<img width="270" alt="image" src="https://user-images.githubusercontent.com/107703532/234890463-4ef94c7b-b066-4183-8d1b-d9d67f8ccaf8.png">

**Comment by Run37927** [comment]
would love to help on this issue.
