### ISSUE TITLE
Change Pagination to Infinite Scroll

### ISSUE THREAD

**Issue by RateTheLandlordAdmin** [RateTheLandlord/RateTheLandlord#192]

**Comment by RateTheLandlordAdmin** [comment]
https://swr.vercel.app/docs/pagination#infinite-loading

**Comment by ritesh-pandey** [comment]
We need a way to populate database with dummy data. This data can then be used to develop and test "infinite scroll" feature.

**Comment by RateTheLandlordAdmin** [comment]
@ritesh-pandey changing the `reviews` page SWR endpoint to `https://ratethelandlord.org/api/get-reviews` should resolve with reviews from the site itself.

**Comment by RateTheLandlordAdmin** [comment]
@ritesh-pandey Are you going to tackle this issue?

**Comment by ritesh-pandey** [comment]
> @ritesh-pandey changing the `reviews` page SWR endpoint to `https://ratethelandlord.org/api/get-reviews` should resolve with reviews from the site itself.

AJAX request from local environment to production endpoint will be a cross origin request. Appropriate CORS headers are not set on production response. Hence the request will get blocked by browser.

**Comment by RateTheLandlordAdmin** [comment]
Still thinking of an appropriate solution for this. 

You could try an SQL query in the Postgres container to push records into the `review` table?

**Comment by RateTheLandlordAdmin** [comment]
That would be a great solution!
