### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by larsiusprime** [RateTheLandlord/RateTheLandlord#205]
I was curious what license this project is released under, as there is no license text file I can find. Is it meant to be open source? And if so, Copyleft/GPL or Permissive/MIT?

**Comment by IanTrudel** [comment]
There is no point to contribute as long as there is no license. The project has everything to guide us to the very exception of a license.

The code should currently be considered as copyrighted where forking and running your own version would get you in legal troubles.

Contributing to a project without a license prevents you to know the rules of engagement and brings questions of ownership, liabilities and the context the contribution can and/or will be used.

**DO NOT FORK OR CONTRIBUTE** until a license has been established.

@kellenwiltshire , @RateTheLandlordAdmin

**Comment by RateTheLandlordAdmin** [comment]
License is in the process of being added. Will be there today once Github resolves its issues.

**Comment by IanTrudel** [comment]
Excellent, thank you.
