### ISSUE TITLE
City Moscow in Idaho missing from cities list

### ISSUE THREAD

**Issue by turkeydonkey** [RateTheLandlord/RateTheLandlord#206]
When scrolling the cities list, Moscow is missing. Moscow is a medium size city in Latah county, Idaho. It's the home of the University of Idaho, so it's likely there are many students in off campus housing who would like to write reviews.

**Comment by RateTheLandlordAdmin** [comment]
Cities are added based on the reviews received. If a city is not on the list then it means the site hasn't received a review from that city yet.
