### ISSUE TITLE
Use input field for ZIP / Postal code field

### ISSUE THREAD

**Issue by Marrzz** [RateTheLandlord/RateTheLandlord#208]
Currently ZIP code filter is displayed as a dropdown with an increasing amount of values. Currently this dropdown displays over 3000 values. Due to the amount of values and you mapping them into objects to be displayed it takes way too long for the dropdown to open for it to be a useful filter.

I suggest abandoning the dropdown and using a regular input box instead. This eliminates the need for mapping the values and thus the performance issues.

**Comment by kylehgc** [comment]
I didn't see your comment before opening the issue but its actually a problem with the underlying UI library and the same problem is happening with the city pulldown.   https://github.com/tailwindlabs/headlessui/issues/474 There is a fix in this thread to implement virtualization that should fix it.  Its going to come up as a problem with all the drop downs eventually as people are saying that there are performance issues with 150 options so even countries are going to start having problems. Its also apparently rerendering the whole list on hover.
