### ISSUE TITLE
Add Autofill/Suggestions to Create Review Form

### ISSUE THREAD

**Issue by RateTheLandlordAdmin** [RateTheLandlord/RateTheLandlord#265]
On Landlord Name and city should show suggested inputs underneath while the user is typing. This will allow Landlords to be better grouped together (Landlord Name LTD vs Landlord Name) and prevent spelling errors.

If the city or name doesn't exist then it should function as normal and the new entry is created

**Comment by jallen2034** [comment]
Hello,

My friend and I are thrilled to take on the challenge of incorporating this functionality into the web app as React developers ourselves. We're confident in our skills and are excited to pair program together on this task. Before we begin, we want to ensure that we have a thorough understanding of the feature and any design preferences or technical constraints you may have. Clear guidance from you will help us deliver the best implementation possible.

In addition, we were wondering if you have a Discord/Slack channel or any other platform where we might be able to collaborate in real-time. Having a dedicated space for communication and idea sharing will enable us to work more efficiently and effectively :) 

Thank you for considering us for this project. We are looking forward to collaborating with you!

**Comment by RateTheLandlordAdmin** [comment]
Hi There,

Thanks for your interest in contributing! 

What we are envisioning for the functionality is a lot like how you search for a location with Google Maps, or when you use any search engine and it tries to "predict" what you are typing out. 

I think it would be easiest to tie this into the current landlord state. Once the landlord name length gets over 3 characters, it should query the back (either with a POST or a GET) to return a list of landlords with those characters in their name (similar to how the filtering functions work now on the reviews page for Province, City and Postal Code. The difference is if nothing is returned, then we can just assume they are making a new entry for a landlord we don't have already.

A custom hook might be the way to go here on the frontend. The backend should be a quick fix to add a new route to the review route that is either a POST or a GET (with query) that trigger a DB query to return an array of Landlord names that match the input so far. 

Hope that helps!

As for the Discord, I just put the invite link in the About section for the Repo.

Thanks again for the assistance!

**Comment by kellenwiltshire** [comment]
This should update should also block the special characters of `(, ), /, \, @, #, $, %, ^, *, <, >, ?, [, ], {, }, |`
