### ISSUE TITLE
duplicate city names bc no location api

### ISSUE THREAD

**Issue by goatandsheep** [RateTheLandlord/RateTheLandlord#291]
**Is your feature request related to a problem? Please describe.**
Duplicate city names, for example, search Toronto and you get 12 cities.

**Describe the solution you'd like**
City names confirmed with location API

**Comment by kellenwiltshire** [comment]
Possible solution to this issue with this API:

`https://nominatim.openstreetmap.org/search?q={query}&format=json&limit=5&addressdetails=1`

`query` would need to be updated with what a user has typed in the City field. Would be best to wait until the user stops typing to run the query. Possibly use a custom hook.

**Comment by goatandsheep** [comment]
Aside: thank you so much for starting this amazing website! I honestly hope for the best for its success and happy to help with advice or testing where possible.
