### ISSUE TITLE
Create Missing Tests for Backend

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/RateTheLandlord#292]
**Is your feature request related to a problem? Please describe.**
Backend directory does not have tests for components

**Describe the solution you'd like**
All components in the Backend directory should have tests that pass

**Comment by Run37927** [comment]
will work on this

**Comment by stephenmartin2951** [comment]
Hey Run, did you wrap this up already? If you're open to it, I wouldn't mind tagging along to see how you're working through these if you still have some tests to create.

**Comment by Run37927** [comment]
Pretty much wrapped up! Wrote all the tests for controllers ( well as much
as I can) but haven’t dipped into services tests yet. That requires
creating test database so you can simulate interactions those service
methods with the real db. If you wanna give it a crack definitely go for it
!!
