### ISSUE TITLE
Implement Umami Event Tracking

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/RateTheLandlord#307]
**Is your feature request related to a problem? Please describe.**
We've updated to self-hosting our analytics with Umami, which allows us to track events such as clicks. This needs to be added to buttons and links.

**Describe the solution you'd like**
Follow the [API](https://umami.is/docs/track-events) to implement this feature on buttons and links throughout the site.

**Comment by stephenmartin2951** [comment]
I can take a look at this
