### ISSUE TITLE
Occasionally Empty Strings get accepted for Landlord Name or City

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/RateTheLandlord#343]
**Describe the bug**
Occasionally empty strings get accepted for Landlord Name or City

**Expected behavior**
Empty strings should be checked on both FE and BE. FE shouldn't allow them to be submitted (test with `.trim()` on the string and if length is 0, then show error)

BE should do similar check and not submit into DB with empty string

**Comment by Run37927** [comment]
for BE, create DTOs should do it
